spring:
  application:
    name: marketbee

  config:
    import: optional:application-secret.yml

  datasource:
    url: ${DB_URL}
    driver-class-name: org.mariadb.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

