spring:
  application:
    name: marketbee

  datasource:
    url: jdbc:mariadb://localhost:3306/marketbee?useUnicode=true&characterEncoding=utf8mb4
    driver-class-name: org.mariadb.jdbc.Driver
    username: {root}
    password: {rlslelfl123!!}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true
