spring:
  application:
    name: marketbee

  config:
    import: optional:application-secret.yml

  datasource:
    url: jdbc:mariadb://localhost:3306/marketbee?useUnicode=true&characterEncoding=utf8mb4
    driver-class-name: org.mariadb.jdbc.Driver
    username: {root}
    password: {rlslelfl123!!}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB